security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        register:
            pattern: ^/api/user-create
            stateless: true
            security: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login_check$
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path:    /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            provider:  app_user_provider

            jwt: ~

            refresh_jwt:
                check_path: /api/token/refresh
            entry_point: jwt
        main:
            lazy: true
            provider: app_user_provider
            entry_point: lexik_jwt_authentication.jwt_manager
 
    access_control:
        - { path: ^/api/user-create, methods: [ POST ], roles: PUBLIC_ACCESS }
        - { path: ^/api/confirmation-compte/, methods: [ GET ], roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh$, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check$,   roles: PUBLIC_ACCESS }
        - { path: ^/api/login,          roles: PUBLIC_ACCESS }
        - { path: ^/api/forgot-password, methods: [ POST ], roles: PUBLIC_ACCESS }
        - { path: ^/api/reset-password/, methods: [ POST ], roles: PUBLIC_ACCESS }
        - { path: ^/api/quiz/organized, methods: [ GET ], roles: PUBLIC_ACCESS }

        - { path: ^/api/quiz/list$, methods: [ GET ], roles: PUBLIC_ACCESS }
        - { path: ^/api/quiz/[0-9]+$, methods: [ GET ], roles: PUBLIC_ACCESS }
        - { path: ^/api/quiz/organized$, methods: [ GET ], roles: PUBLIC_ACCESS }
        - { path: ^/api/quiz/[0-9]+/average-rating$, methods: [ GET ], roles: PUBLIC_ACCESS }
        - { path: ^/api/quiz/[0-9]+/public-leaderboard$, methods: [ GET ], roles: PUBLIC_ACCESS }
        - { path: ^/api/category-quiz, methods: [ GET ], roles: PUBLIC_ACCESS }

        - { path: ^/api/game, roles: PUBLIC_ACCESS }
        - { path: ^/api/donations, roles: PUBLIC_ACCESS }

        - { path: ^/api/companies, roles: ROLE_ADMIN }

        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
