security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        register:
            pattern: ^/api/user-create
            stateless: true
            security: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login_check$
            stateless: true
            provider: app_user_provider
            json_login:
                check_path:    /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            provider:  app_user_provider

            jwt: ~

            refresh_jwt:
                check_path: /api/token/refresh
            entry_point: jwt
        main:
            lazy: true
            provider: app_user_provider
            entry_point: lexik_jwt_authentication.jwt_manager

    access_control:
        - { path: ^/api/user-create, methods: [ POST ], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login_check$,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
