# Version simplifiée pour GitHub Actions
name: CI/CD Pipeline - Tests et Qualité

on:
  push:
    branches: [ main, dev-admin-crud, develop ]
  pull_request:
    branches: [ main, dev-admin-crud, develop ]

jobs:
  test:
    name: Tests et Qualité
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, pdo_sqlite, zip, gd
        coverage: xdebug

    - name: Install dependencies
      run: |
        cd back
        composer install --prefer-dist --no-progress

    - name: Setup test database (SQLite)
      run: |
        cd back
        echo "APP_ENV=test" > .env
        echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
        echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/test.db" >> .env
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:migrations:migrate --env=test --no-interaction

    - name: Run tests
      run: |
        cd back
        php bin/phpunit

    - name: Run PHPStan
      run: |
        cd back
        vendor/bin/phpstan analyse src/ --level=5

    - name: Run PHP CS Fixer
      run: |
        cd back
        vendor/bin/php-cs-fixer fix --dry-run --diff
