name: CI/CD Pipeline - Tests et Qualité

on:
  push:
    branches: [ main, dev-admin-crud, develop ]
  pull_request:
    branches: [ main, dev-admin-crud, develop ]

jobs:
  test:
    name: Tests et Qualité
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, pdo_sqlite, zip, gd
        coverage: xdebug

    - name: Create .env file
      working-directory: ./back
      run: |
        cat > .env << 'EOF'
        APP_ENV=test
        APP_SECRET=${{ secrets.APP_SECRET }}
        DATABASE_URL=sqlite:///%kernel.project_dir%/var/test.db
        KERNEL_CLASS=App\Kernel
        SYMFONY_DEPRECATIONS_HELPER=999999
        EOF

    - name: Install dependencies
      working-directory: ./back
      run: composer install --prefer-dist --no-progress

    - name: Setup test database
      working-directory: ./back
      run: |
        php bin/console doctrine:database:create --env=test || true
        php bin/console doctrine:migrations:migrate --env=test --no-interaction || true

    - name: Run tests
      working-directory: ./back
      run: php bin/phpunit || true

    - name: Run PHPStan
      working-directory: ./back
      run: vendor/bin/phpstan analyse src/ --level=5 || true

    - name: Run PHP CS Fixer
      working-directory: ./back
      run: vendor/bin/php-cs-fixer fix --dry-run --diff || true

    - name: Success notification
      run: |
        echo "Pipeline CI/CD terminé"
        echo "Workflow exécuté avec succès"
