name: CI/CD Pipeline - Tests et Qualité

on:
  push:
    branches: [ main, dev-admin-crud, develop ]
  pull_request:
    branches: [ main, dev-admin-crud, develop ]

jobs:
  test:
    name: Tests et Qualité
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, pdo_sqlite, zip, gd
        coverage: xdebug

    - name: Install dependencies
      working-directory: ./back
      run: composer install --prefer-dist --no-progress

    - name: Setup test database
      working-directory: ./back
      env:
        APP_ENV: test
        APP_SECRET: ${{ secrets.APP_SECRET }}
        DATABASE_URL: sqlite:///%kernel.project_dir%/var/test.db
      run: |
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:migrations:migrate --env=test --no-interaction

    - name: Run tests
      working-directory: ./back
      env:
        APP_ENV: test
        APP_SECRET: ${{ secrets.APP_SECRET }}
        DATABASE_URL: sqlite:///%kernel.project_dir%/var/test.db
      run: php bin/phpunit

    - name: Run PHPStan
      working-directory: ./back
      run: vendor/bin/phpstan analyse src/ --level=5

    - name: Run PHP CS Fixer
      working-directory: ./back
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Success notification
      run: |
        echo "Pipeline CI/CD terminé avec succès"
        echo "Tests: PASSED"
        echo "Qualité: PASSED"
        echo "Code prêt pour le déploiement"
